repos:
-   repo: https://github.com/ambv/black
    rev: cb67a322423cb2b4bcfb2faa68fb769326741d6a
    hooks:
    - id: black
      args: []
      python_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    -   id: flake8
